### PR TITLE
Suggestions for the ECU Hard Reset

### PR DESCRIPTION
**Pull request by shipcod3**
You don't need to send the same data with a different ID on this one. But my suggestions really, is to create options what are the UDS IDs on this one. 7DF is one of the standards and so is 7E1 but it could be different to other vehicles and not both of those IDs. You need to have an option to choose what ID and not just those two.

### CODE REVIEW

**Comment by souravbaghz** [comment]
Agreed, Thanks for your suggestion. I will add an input option for this.

**Comment by souravbaghz** [comment]
option for custom arbitary id has been added.

**Comment by shipcod3** [comment]
okay but why is it sending 2 the same messages for the default ECU hard reset? It should be only one. I am not sure how you got the idea that 2 messages should be sent simultaneously to do an ECU hard reset.

**Comment by souravbaghz** [comment]
You have point, I had added it thought of if one doesn't work then second will, anyway now there is one and second one has been commented.

**Comment by shipcod3** [comment]
that's good

**Pull request closed without merging**
